server:
  port: 8081
spring:
  cloud:
    stream:
      bindings:
        input:
          destination: shareoo-exchange
          binder: shareoo-stream
          group: shareoo
          content-type: application/json
      binders:
        shareoo-stream:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
  application:
    name: shareoo-services
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}